# Generated by Django 4.1 on 2022-08-14 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=300, unique=True)),
                (
                    "school_category",
                    models.CharField(
                        choices=[
                            ("Public School", "Public School"),
                            ("Private School", "Private School"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("school_address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("email_field", models.EmailField(max_length=254)),
                (
                    "school_cert",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "registeration_cert",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "ministry_approval",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "proprietor_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "proprietor_email",
                    models.EmailField(blank=True, max_length=250, null=True),
                ),
                (
                    "proprietor_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "principal_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "principal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "principal_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "bursar_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "bursar_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "bursar_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_student", models.CharField(max_length=50)),
                ("name_of_parent", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("slug", models.SlugField()),
                ("school_owed", models.CharField(max_length=250)),
                ("amount_owed", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Abandoned payment", "Abandoned payment"),
                            ("Pending payment", "Pending payment"),
                            ("Completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.registrationclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
