# Generated by Django 4.1 on 2022-08-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationclass",
            name="email_field",
        ),
        migrations.RemoveField(
            model_name="registrationclass",
            name="user_name",
        ),
        migrations.AddField(
            model_name="registrationclass",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="registrationclass",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="registrationclass",
            name="bursar_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="registrationclass",
            name="contact_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="registrationclass",
            name="principal_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="registrationclass",
            name="proprietor_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="registrationclass",
            name="school_category",
            field=models.CharField(
                choices=[("Public", "Public School"), ("Private", "Private School")],
                default="Public",
                max_length=20,
            ),
        ),
    ]
