# Generated by Django 4.1 on 2022-08-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=300, unique=True)),
                (
                    "school_category",
                    models.CharField(
                        choices=[
                            ("Public School", "Public School"),
                            ("Private School", "Private School"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("school_address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("email_field", models.EmailField(max_length=254)),
                (
                    "school_cert",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "registeration_cert",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "ministry_approval",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "proprietor_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "principal_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "proprietor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "proprietor_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "bursar_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "bursar_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "bursar_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
