# Generated by Django 4.1 on 2022-08-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_contendform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="records",
            name="school",
        ),
        migrations.AddField(
            model_name="records",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
