# Generated by Django 4.1 on 2022-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_remove_records_school_records_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="records",
            name="evidence",
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
